language: java
jdk:
- oraclejdk8
before_install:
 openssl aes-256-cbc -K $encrypted_34b0a67ff0bb_key -iv $encrypted_34b0a67ff0bb_iv
 -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
