language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
